# Site settings é…ç½®ç«™ç‚¹
title: 'FAN Bot'
description: 'your web description'
keywords: 'Robot, Machine Learning, Wood Skill, Worldwide Journey'
url: 'https://Xiaofan-Shen.github.io' # your host

defaults:
  scope:
    path: ""
    type: "pages"
  values:
    permalink: "/about/:title/"

# nav ä¸­æ–‡å­—ç¬¦ç©ºæ ¼ï¼š&emsp;
nav: # æœ€ä½³ä½“éªŒ å…­ä¸ªæ ‡ç­¾ ä¸”æœ€å¥½æ¯ä¸ªæ ‡ç­¾ä¸è¶…è¿‡4ä¸­æ–‡å­—
  Homepage: '/about.html'
  My Projects: '/'
  Timeline: '/timeline.html'
  Tags: '/tags.html'
  My Fancy Trip: '/mytrip.html'
  # Link: '/friendLink.html'

# åšä¸»
author: true
name: 'Fan'
NickName: 'Fan'
webtitle: "Fan's Robot Lab"
bio: "Hey thereğŸ˜Š, I'm Xiaofan Shen."
about: true
aboutyou: "I graduated with a bachelor's degree in Electrical Engineering from the University of Liverpool, and later switched gears to pursue a master's at UCL in Robotics and Computation. I have a deep passion for technology, and I particularly enjoy tinkering with Raspberry Pi to create fun and interesting projects.
<br>I have two dogs and one cat. I am located in both the UK and China. I love going on self-driving hikes and camping trips with my furry friends. I also have a passion for traveling, exploring the local customs of different countries and regions, and capturing stories through my camera lens.
<hr>
<p><strong>Education & Work</strong></p>

<blockquote>ğŸ“University College London, MSc Robotics & Computation 
<br> ğŸ“University of Liverpool, BEng Electrical Engineering  
<br> ğŸ’¼Engineer, EMERSON Automation. <em>Beijing, China. July 2020 to Aug. 2021</em>
<br> ğŸ’¼Intern, Otong Electric Company.<em> Shanghai, China. Jan. 2019 to May 2019</em>
<br> ğŸ’¼Intern, Siemens Electrical Apparatus Ltd. <em>Suzhou, China. Jan. 2018 to Mar. 2018</em>
</blockquote> 

<p><strong>Research Interests </strong></p>
<blockquote> ğŸ¤–Robotics
<br> ğŸ•¶ï¸Virtual Reality (VR)
<br> ğŸ“ŠImage Processing
<br>ğŸ”Search Algorithms  
<br> ğŸPython Programming
<br> âš™ï¸Machine Learning: k-Nearest Neighbors, kNN, Decision Tree, Support Vector Machine, Neural Network, Clustering
</blockquote> 
 
"
# ä¸¤æ ç¤ºä¾‹
columns:
  - title: "å·¦æ æ ‡é¢˜"
    content:
      - "å·¦æ å†…å®¹1"
      - "å·¦æ å†…å®¹2"
      - "å·¦æ å†…å®¹3"

  - title: "å³æ æ ‡é¢˜"
    content:
      - "å³æ å†…å®¹1"
      - "å³æ å†…å®¹2"
      - "å³æ å†…å®¹3"

portraits: '/assets/Fanpic.png' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  # mail: 'mailto:abc@gmail.com'
  weixin: '/assets/photos/QRcode_wechat.jpg'
  #qq: '' # ä½ çš„qqäºŒç»´ç å­˜æ”¾çš„åœ°å€ or http://wpa.qq.com/msgrd?v=3&uin='ä½ çš„QQå·'&site=qq&menu=yes
  linkedin: 'https://www.linkedin.com/in/xiaofan-shen/'
  github: 'https://github.com/Xiaofan-Shen'
  #Codepen: ''
  #weibo: ''
  instagram: 'https://www.instagram.com/shenxiaofan0303/'
  Twitter: 'https://twitter.com/XiaofanSHEN0303'
 # Dribbble: ''
 # Facebook: ''
 # Google: ''
 # zhihu: ''
 # juejin: ''
 # twitch: ''

# åˆ†é¡µ
paginate: 10
paginatepath: ['page:num']
source: ''

# since
footer:
  since: 2023

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# ä»£ç é«˜äº® ä½¿ç”¨rouge
highlighter: rouge
# ä»£ç é«˜äº®ä¸»é¢˜ä½¿ç”¨pygmentsä¸»é¢˜: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango ä»»é€‰ä¸€ä¸ªä½ å–œæ¬¢çš„ä¸»é¢˜åç§°å¡«åœ¨ä¸‹é¢çš„å•å¼•å·ä¸­
pygmentsTheme: 'default'

# å‹æƒ…é“¾æ¥
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# è¯„è®º æœ€ä½³ä½“éªŒ åœ¨disqusã€livereå’ŒGitmentä¹‹é—´ä¸‰é€‰ä¸€
# disqus è¯„è®º
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# æ¥å¿…åŠ›è¯„è®º
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitmentè¯„è®º OAuth Application
Gitment: false
Gitment_owner: ''  # githubç”¨æˆ·å
Gitment_repo: ''  # githubåšå®¢å­˜æ”¾çš„ä»“åº“å
client_id: ''  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_id
client_secret: ''  # æ³¨å†Œ OAuth Application åè·å¾—çš„ client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# ç™¾åº¦ç»Ÿè®¡ åœ¨baidu-urlé‡Œå¡«å†™è‡ªå·±ç›¸å…³çš„urlä»£ç 
baidu: true
baidu-url: ''
# è°·æ­Œåˆ†æ åœ¨google-IDé‡Œå¡«å†™è‡ªå·±åœ¨è°·æ­Œåˆ†æè·å¾—çš„è¿½è¸ªID
google: true
google-ID: 'G-5FZ705XRJX'

# åšå®¢å¤´ä¿¡æ¯å¤‡é€‰é¢œè‰²ï¼ˆè¯¥éƒ¨åˆ†åœ¨ç«™ç‚¹ä¸­ä¸å……å½“ç«™ç‚¹å˜é‡ï¼Œå°†å…¶å†™åœ¨postçš„å¤´ä¿¡æ¯ä¸­ç”¨æ¥å……å½“é¡µé¢å˜é‡ï¼‰
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
